### ISSUE TITLE
Model Resource

### ISSUE THREAD

**Issue by Jake-NSW** [Woosh-Crew/Espionage.Engine#33]
**Is your feature request related to a problem? Please describe.**
Currently, having models / visuals directly on a Prefab / Blueprint is pretty stupid to me. Maybe we can make it a separate asset type? This would also allow modders to only change visuals on blueprints. Instead of the whole thing.

**Describe the solution you'd like**
Models API similar to how UI and Textures work.

**Additional Context**
This would not work for static models, or loaded in editor. As Unity gets real stupid with that.

**Comment by Geeknerd1337** [comment]
My biggest concern with this would be that you'd end up making the job of a regular developer longer for the sake of potentially making something easier for a modder. Plus you create an issue where your scripts and code need references to models, and what if a prefab is made up of multiple models? Setting stuff like animator parameters becomes a pain then.

**Comment by Jake-NSW** [comment]
Since we are changing to a more code driven workflow, This is now imporant
